/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright © 2009, Eracash.com"
#property link      "http://www.eracash.com"
#property show_inputs

extern int MMType = 1;
extern bool UseClose = FALSE;
bool gi_84 = TRUE;
double gd_88 = 1.667;
double g_slippage_96 = 3.0;
extern double Lots = 0.01;
double gd_112 = 2.0;
double g_pips_120 = 10.0;
double g_pips_128 = 0.0;
double gd_136 = 10.0;
double gd_144 = 10.0;
double g_pips_152 = 5.0;
extern int MaxTrades = 10;
extern bool UseEquityStop = FALSE;
extern double TotalEquityRisk = 20.0;
extern bool UseTrailingStop = FALSE;
extern bool UseTimeOut = FALSE;
extern double MaxTradeOpenHours = 48.0;
extern bool TimeFilter = FALSE;
extern int StartHour = 2;
extern int EndHour = 16;
int g_magic_204 = 12324;
double g_price_208;
double gd_216;
double gd_unused_224;
double gd_unused_232;
double g_price_240;
double g_bid_248;
double g_ask_256;
double gd_264;
double gd_272;
double gd_280;
bool gi_288;
string gs_292 = "Robot Forex 2014 Profesional";
int g_time_300 = 0;
int gi_304;
int gi_308 = 0;
double gd_312;
int g_pos_320 = 0;
int gi_324;
double gd_328 = 0.0;
bool gi_336 = FALSE;
bool gi_340 = FALSE;
bool gi_344 = FALSE;
int gi_348;
bool gi_352 = FALSE;
int g_datetime_356 = 0;
int g_datetime_360 = 0;
double gd_364;
double gd_372;

int init() {
   gd_280 = MarketInfo(Symbol(), MODE_SPREAD) * Point;
   if (IsTesting() == TRUE) Display_Info();
   if (IsTesting() == FALSE) Display_Info();
   return (0);
}

int deinit() {
   return (0);
}

int start() {
   double l_ord_lots_0;
   double l_ord_lots_8;
   double l_iclose_16;
   double l_iclose_24;
   string ls_32 = "false";
   string ls_40 = "false";
   if (TimeFilter == FALSE || (TimeFilter && (EndHour > StartHour && (Hour() >= StartHour && Hour() <= EndHour)) || (StartHour > EndHour && !(Hour() >= EndHour && Hour() <= StartHour)))) ls_32 = "true";
   if (TimeFilter && (EndHour > StartHour && !(Hour() >= StartHour && Hour() <= EndHour)) || (StartHour > EndHour && (Hour() >= EndHour && Hour() <= StartHour))) ls_40 = "true";
   if (UseTrailingStop) TrailingAlls(gd_136, gd_144, g_price_240);
   if (UseTimeOut) {
      if (TimeCurrent() >= gi_304) {
         CloseThisSymbolAll();
         Print("Closed All due to TimeOut");
      }
   }
   if (g_time_300 == Time[0]) return (0);
   g_time_300 = Time[0];
   double ld_48 = CalculateProfit();
   if (UseEquityStop) {
      if (ld_48 < 0.0 && MathAbs(ld_48) > TotalEquityRisk / 100.0 * AccountEquityHigh()) {
         CloseThisSymbolAll();
         Print("Closed All due to Stop Out");
         gi_352 = FALSE;
      }
   }
   gi_324 = CountTrades();
   if (gi_324 == 0) gi_288 = FALSE;
   for (g_pos_320 = OrdersTotal() - 1; g_pos_320 >= 0; g_pos_320--) {
      OrderSelect(g_pos_320, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
         if (OrderType() == OP_BUY) {
            gi_340 = TRUE;
            gi_344 = FALSE;
            l_ord_lots_0 = OrderLots();
            break;
         }
      }
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
         if (OrderType() == OP_SELL) {
            gi_340 = FALSE;
            gi_344 = TRUE;
            l_ord_lots_8 = OrderLots();
            break;
         }
      }
   }
   if (gi_324 > 0 && gi_324 <= MaxTrades) {
      RefreshRates();
      gd_264 = FindLastBuyPrice();
      gd_272 = FindLastSellPrice();
      if (gi_340 && gd_264 - Ask >= g_pips_152 * Point) gi_336 = TRUE;
      if (gi_344 && Bid - gd_272 >= g_pips_152 * Point) gi_336 = TRUE;
   }
   if (gi_324 < 1) {
      gi_344 = FALSE;
      gi_340 = FALSE;
      gi_336 = TRUE;
      gd_216 = AccountEquity();
   }
   if (gi_336) {
      gd_264 = FindLastBuyPrice();
      gd_272 = FindLastSellPrice();
      if (gi_344) {
         if (UseClose || ls_40 == "true") {
            fOrderCloseMarket(0, 1);
            gd_312 = NormalizeDouble(gd_88 * l_ord_lots_8, gd_112);
         } else gd_312 = fGetLots(OP_SELL);
         if (gi_84 && ls_32 == "true") {
            gi_308 = gi_324;
            if (gd_312 > 0.0) {
               RefreshRates();
               gi_348 = OpenPendingOrder(1, gd_312, Bid, g_slippage_96, Ask, 0, 0, gs_292 + "-" + gi_308, g_magic_204, 0, HotPink);
               if (gi_348 < 0) {
                  Print("Error: ", GetLastError());
                  return (0);
               }
               gd_272 = FindLastSellPrice();
               gi_336 = FALSE;
               gi_352 = TRUE;
            }
         }
      } else {
         if (gi_340) {
            if (UseClose || ls_40 == "true") {
               fOrderCloseMarket(1, 0);
               gd_312 = NormalizeDouble(gd_88 * l_ord_lots_0, gd_112);
            } else gd_312 = fGetLots(OP_BUY);
            if (gi_84 && ls_32 == "true") {
               gi_308 = gi_324;
               if (gd_312 > 0.0) {
                  gi_348 = OpenPendingOrder(0, gd_312, Ask, g_slippage_96, Bid, 0, 0, gs_292 + "-" + gi_308, g_magic_204, 0, Lime);
                  if (gi_348 < 0) {
                     Print("Error: ", GetLastError());
                     return (0);
                  }
                  gd_264 = FindLastBuyPrice();
                  gi_336 = FALSE;
                  gi_352 = TRUE;
               }
            }
         }
      }
   }
   if (gi_336 && gi_324 < 1) {
      l_iclose_16 = iClose(Symbol(), 0, 2);
      l_iclose_24 = iClose(Symbol(), 0, 1);
      g_bid_248 = Bid;
      g_ask_256 = Ask;
      if (!gi_344 && !gi_340 && ls_32 == "true") {
         gi_308 = gi_324;
         if (l_iclose_16 > l_iclose_24) {
            gd_312 = fGetLots(OP_SELL);
            if (gd_312 > 0.0) {
               gi_348 = OpenPendingOrder(1, gd_312, g_bid_248, g_slippage_96, g_bid_248, 0, 0, gs_292 + "-" + gi_308, g_magic_204, 0, HotPink);
               if (gi_348 < 0) {
                  Print(gd_312, "Error: ", GetLastError());
                  return (0);
               }
               gd_264 = FindLastBuyPrice();
               gi_352 = TRUE;
            }
         } else {
            gd_312 = fGetLots(OP_BUY);
            if (gd_312 > 0.0) {
               gi_348 = OpenPendingOrder(0, gd_312, g_ask_256, g_slippage_96, g_ask_256, 0, 0, gs_292 + "-" + gi_308, g_magic_204, 0, Lime);
               if (gi_348 < 0) {
                  Print(gd_312, "Error: ", GetLastError());
                  return (0);
               }
               gd_272 = FindLastSellPrice();
               gi_352 = TRUE;
            }
         }
      }
      if (gi_348 > 0) gi_304 = TimeCurrent() + 60.0 * (60.0 * MaxTradeOpenHours);
      gi_336 = FALSE;
   }
   gi_324 = CountTrades();
   g_price_240 = 0;
   double ld_56 = 0;
   for (g_pos_320 = OrdersTotal() - 1; g_pos_320 >= 0; g_pos_320--) {
      OrderSelect(g_pos_320, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
         if (OrderType() == OP_BUY || OrderType() == OP_SELL) {
            g_price_240 += OrderOpenPrice() * OrderLots();
            ld_56 += OrderLots();
         }
      }
   }
   if (gi_324 > 0) g_price_240 = NormalizeDouble(g_price_240 / ld_56, Digits);
   if (gi_352) {
      for (g_pos_320 = OrdersTotal() - 1; g_pos_320 >= 0; g_pos_320--) {
         OrderSelect(g_pos_320, SELECT_BY_POS, MODE_TRADES);
         if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
            if (OrderType() == OP_BUY) {
               g_price_208 = g_price_240 + g_pips_120 * Point;
               gd_unused_224 = g_price_208;
               gd_328 = g_price_240 - g_pips_128 * Point;
               gi_288 = TRUE;
            }
         }
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
            if (OrderType() == OP_SELL) {
               g_price_208 = g_price_240 - g_pips_120 * Point;
               gd_unused_232 = g_price_208;
               gd_328 = g_price_240 + g_pips_128 * Point;
               gi_288 = TRUE;
            }
         }
      }
   }
   if (gi_352) {
      if (gi_288 == TRUE) {
         for (g_pos_320 = OrdersTotal() - 1; g_pos_320 >= 0; g_pos_320--) {
            OrderSelect(g_pos_320, SELECT_BY_POS, MODE_TRADES);
            if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
            if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) OrderModify(OrderTicket(), g_price_240, OrderStopLoss(), g_price_208, 0, Yellow);
            gi_352 = FALSE;
         }
      }
   }
   return (0);
}

double ND(double ad_0) {
   return (NormalizeDouble(ad_0, Digits));
}

int fOrderCloseMarket(bool ai_0 = TRUE, bool ai_4 = TRUE) {
   int li_ret_8 = 0;
   for (int l_pos_12 = OrdersTotal() - 1; l_pos_12 >= 0; l_pos_12--) {
      if (OrderSelect(l_pos_12, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
            if (OrderType() == OP_BUY && ai_0) {
               RefreshRates();
               if (!IsTradeContextBusy()) {
                  if (!OrderClose(OrderTicket(), OrderLots(), ND(Bid), 5, CLR_NONE)) {
                     Print("Error close BUY " + OrderTicket());
                     li_ret_8 = -1;
                  }
               } else {
                  if (g_datetime_356 != iTime(NULL, 0, 0)) {
                     g_datetime_356 = iTime(NULL, 0, 0);
                     Print("Need close BUY " + OrderTicket() + ". Trade Context Busy");
                  }
                  return (-2);
               }
            }
            if (OrderType() == OP_SELL && ai_4) {
               RefreshRates();
               if (!IsTradeContextBusy()) {
                  if (!OrderClose(OrderTicket(), OrderLots(), ND(Ask), 5, CLR_NONE)) {
                     Print("Error close SELL " + OrderTicket());
                     li_ret_8 = -1;
                  }
               } else {
                  if (g_datetime_360 != iTime(NULL, 0, 0)) {
                     g_datetime_360 = iTime(NULL, 0, 0);
                     Print("Need close SELL " + OrderTicket() + ". Trade Context Busy");
                  }
                  return (-2);
               }
            }
         }
      }
   }
   return (li_ret_8);
}

double fGetLots(int a_cmd_0) {
   double l_lots_4;
   int l_datetime_12;
   switch (MMType) {
   case 0:
      l_lots_4 = Lots;
      break;
   case 1:
      l_lots_4 = NormalizeDouble(Lots * MathPow(gd_88, gi_308), gd_112);
      break;
   case 2:
      l_datetime_12 = 0;
      l_lots_4 = Lots;
      for (int l_pos_20 = OrdersHistoryTotal() - 1; l_pos_20 >= 0; l_pos_20--) {
         if (OrderSelect(l_pos_20, SELECT_BY_POS, MODE_HISTORY)) {
            if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
               if (l_datetime_12 < OrderCloseTime()) {
                  l_datetime_12 = OrderCloseTime();
                  if (OrderProfit() < 0.0) l_lots_4 = NormalizeDouble(OrderLots() * gd_88, gd_112);
                  else l_lots_4 = Lots;
               }
            }
         } else return (-3);
      }
   }
   if (AccountFreeMarginCheck(Symbol(), a_cmd_0, l_lots_4) <= 0.0) return (-1);
   if (GetLastError() == 134/* NOT_ENOUGH_MONEY */) return (-2);
   return (l_lots_4);
}

int CountTrades() {
   int l_count_0 = 0;
   for (int l_pos_4 = OrdersTotal() - 1; l_pos_4 >= 0; l_pos_4--) {
      OrderSelect(l_pos_4, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204)
         if (OrderType() == OP_SELL || OrderType() == OP_BUY) l_count_0++;
   }
   return (l_count_0);
}

void CloseThisSymbolAll() {
   for (int l_pos_0 = OrdersTotal() - 1; l_pos_0 >= 0; l_pos_0--) {
      OrderSelect(l_pos_0, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol()) {
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204) {
            if (OrderType() == OP_BUY) OrderClose(OrderTicket(), OrderLots(), Bid, g_slippage_96, Blue);
            if (OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, g_slippage_96, Red);
         }
         Sleep(1000);
      }
   }
}

int OpenPendingOrder(int ai_0, double a_lots_4, double a_price_12, int a_slippage_20, double ad_24, int ai_unused_32, int ai_36, string a_comment_40, int a_magic_48, int a_datetime_52, color a_color_56) {
   int l_ticket_60 = 0;
   int l_error_64 = 0;
   int l_count_68 = 0;
   int li_72 = 100;
   switch (ai_0) {
   case 2:
      for (l_count_68 = 0; l_count_68 < li_72; l_count_68++) {
         l_ticket_60 = OrderSend(Symbol(), OP_BUYLIMIT, a_lots_4, a_price_12, a_slippage_20, StopLong(ad_24, g_pips_128), TakeLong(a_price_12, ai_36), a_comment_40, a_magic_48, a_datetime_52, a_color_56);
         l_error_64 = GetLastError();
         if (l_error_64 == 0/* NO_ERROR */) break;
         if (!((l_error_64 == 4/* SERVER_BUSY */ || l_error_64 == 137/* BROKER_BUSY */ || l_error_64 == 146/* TRADE_CONTEXT_BUSY */ || l_error_64 == 136/* OFF_QUOTES */))) break;
         Sleep(1000);
      }
      break;
   case 4:
      for (l_count_68 = 0; l_count_68 < li_72; l_count_68++) {
         l_ticket_60 = OrderSend(Symbol(), OP_BUYSTOP, a_lots_4, a_price_12, a_slippage_20, StopLong(ad_24, g_pips_128), TakeLong(a_price_12, ai_36), a_comment_40, a_magic_48, a_datetime_52, a_color_56);
         l_error_64 = GetLastError();
         if (l_error_64 == 0/* NO_ERROR */) break;
         if (!((l_error_64 == 4/* SERVER_BUSY */ || l_error_64 == 137/* BROKER_BUSY */ || l_error_64 == 146/* TRADE_CONTEXT_BUSY */ || l_error_64 == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
      break;
   case 0:
      for (l_count_68 = 0; l_count_68 < li_72; l_count_68++) {
         RefreshRates();
         l_ticket_60 = OrderSend(Symbol(), OP_BUY, a_lots_4, Ask, a_slippage_20, StopLong(Bid, g_pips_128), TakeLong(Ask, ai_36), a_comment_40, a_magic_48, a_datetime_52, a_color_56);
         l_error_64 = GetLastError();
         if (l_error_64 == 0/* NO_ERROR */) break;
         if (!((l_error_64 == 4/* SERVER_BUSY */ || l_error_64 == 137/* BROKER_BUSY */ || l_error_64 == 146/* TRADE_CONTEXT_BUSY */ || l_error_64 == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
      break;
   case 3:
      for (l_count_68 = 0; l_count_68 < li_72; l_count_68++) {
         l_ticket_60 = OrderSend(Symbol(), OP_SELLLIMIT, a_lots_4, a_price_12, a_slippage_20, StopShort(ad_24, g_pips_128), TakeShort(a_price_12, ai_36), a_comment_40, a_magic_48, a_datetime_52, a_color_56);
         l_error_64 = GetLastError();
         if (l_error_64 == 0/* NO_ERROR */) break;
         if (!((l_error_64 == 4/* SERVER_BUSY */ || l_error_64 == 137/* BROKER_BUSY */ || l_error_64 == 146/* TRADE_CONTEXT_BUSY */ || l_error_64 == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
      break;
   case 5:
      for (l_count_68 = 0; l_count_68 < li_72; l_count_68++) {
         l_ticket_60 = OrderSend(Symbol(), OP_SELLSTOP, a_lots_4, a_price_12, a_slippage_20, StopShort(ad_24, g_pips_128), TakeShort(a_price_12, ai_36), a_comment_40, a_magic_48, a_datetime_52, a_color_56);
         l_error_64 = GetLastError();
         if (l_error_64 == 0/* NO_ERROR */) break;
         if (!((l_error_64 == 4/* SERVER_BUSY */ || l_error_64 == 137/* BROKER_BUSY */ || l_error_64 == 146/* TRADE_CONTEXT_BUSY */ || l_error_64 == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
      break;
   case 1:
      for (l_count_68 = 0; l_count_68 < li_72; l_count_68++) {
         l_ticket_60 = OrderSend(Symbol(), OP_SELL, a_lots_4, Bid, a_slippage_20, StopShort(Ask, g_pips_128), TakeShort(Bid, ai_36), a_comment_40, a_magic_48, a_datetime_52, a_color_56);
         l_error_64 = GetLastError();
         if (l_error_64 == 0/* NO_ERROR */) break;
         if (!((l_error_64 == 4/* SERVER_BUSY */ || l_error_64 == 137/* BROKER_BUSY */ || l_error_64 == 146/* TRADE_CONTEXT_BUSY */ || l_error_64 == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
   }
   return (l_ticket_60);
}

double StopLong(double ad_0, int ai_8) {
   if (ai_8 == 0) return (0);
   return (ad_0 - ai_8 * Point);
}

double StopShort(double ad_0, int ai_8) {
   if (ai_8 == 0) return (0);
   return (ad_0 + ai_8 * Point);
}

double TakeLong(double ad_0, int ai_8) {
   if (ai_8 == 0) return (0);
   return (ad_0 + ai_8 * Point);
}

double TakeShort(double ad_0, int ai_8) {
   if (ai_8 == 0) return (0);
   return (ad_0 - ai_8 * Point);
}

double CalculateProfit() {
   double ld_ret_0 = 0;
   for (g_pos_320 = OrdersTotal() - 1; g_pos_320 >= 0; g_pos_320--) {
      OrderSelect(g_pos_320, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204)
         if (OrderType() == OP_BUY || OrderType() == OP_SELL) ld_ret_0 += OrderProfit();
   }
   return (ld_ret_0);
}

void TrailingAlls(int ai_0, int ai_4, double a_price_8) {
   int li_16;
   double l_ord_stoploss_20;
   double l_price_28;
   if (ai_4 != 0) {
      for (int l_pos_36 = OrdersTotal() - 1; l_pos_36 >= 0; l_pos_36--) {
         if (OrderSelect(l_pos_36, SELECT_BY_POS, MODE_TRADES)) {
            if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
            if (OrderSymbol() == Symbol() || OrderMagicNumber() == g_magic_204) {
               if (OrderType() == OP_BUY) {
                  li_16 = NormalizeDouble((Bid - a_price_8) / Point, 0);
                  if (li_16 < ai_0) continue;
                  l_ord_stoploss_20 = OrderStopLoss();
                  l_price_28 = Bid - ai_4 * Point;
                  if (l_ord_stoploss_20 == 0.0 || (l_ord_stoploss_20 != 0.0 && l_price_28 > l_ord_stoploss_20)) OrderModify(OrderTicket(), a_price_8, l_price_28, OrderTakeProfit(), 0, Aqua);
               }
               if (OrderType() == OP_SELL) {
                  li_16 = NormalizeDouble((a_price_8 - Ask) / Point, 0);
                  if (li_16 < ai_0) continue;
                  l_ord_stoploss_20 = OrderStopLoss();
                  l_price_28 = Ask + ai_4 * Point;
                  if (l_ord_stoploss_20 == 0.0 || (l_ord_stoploss_20 != 0.0 && l_price_28 < l_ord_stoploss_20)) OrderModify(OrderTicket(), a_price_8, l_price_28, OrderTakeProfit(), 0, Red);
               }
            }
            Sleep(1000);
         }
      }
   }
}

double AccountEquityHigh() {
   if (CountTrades() == 0) gd_364 = AccountEquity();
   if (gd_364 < gd_372) gd_364 = gd_372;
   else gd_364 = AccountEquity();
   gd_372 = AccountEquity();
   return (gd_364);
}

double FindLastBuyPrice() {
   double l_ord_open_price_0;
   int l_ticket_8;
   double ld_unused_12 = 0;
   int l_ticket_20 = 0;
   for (int l_pos_24 = OrdersTotal() - 1; l_pos_24 >= 0; l_pos_24--) {
      OrderSelect(l_pos_24, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204 && OrderType() == OP_BUY) {
         l_ticket_8 = OrderTicket();
         if (l_ticket_8 > l_ticket_20) {
            l_ord_open_price_0 = OrderOpenPrice();
            ld_unused_12 = l_ord_open_price_0;
            l_ticket_20 = l_ticket_8;
         }
      }
   }
   return (l_ord_open_price_0);
}

double FindLastSellPrice() {
   double l_ord_open_price_0;
   int l_ticket_8;
   double ld_unused_12 = 0;
   int l_ticket_20 = 0;
   for (int l_pos_24 = OrdersTotal() - 1; l_pos_24 >= 0; l_pos_24--) {
      OrderSelect(l_pos_24, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != g_magic_204) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == g_magic_204 && OrderType() == OP_SELL) {
         l_ticket_8 = OrderTicket();
         if (l_ticket_8 > l_ticket_20) {
            l_ord_open_price_0 = OrderOpenPrice();
            ld_unused_12 = l_ord_open_price_0;
            l_ticket_20 = l_ticket_8;
         }
      }
   }
   return (l_ord_open_price_0);
}

void Display_Info() {
   Comment("Robot Forex 2014 Profesional EURUSD M15\n", "Forex Account Server:", AccountServer(), 
      "\n", "Lots:  ", Lots, 
      "\n", "Symbol: ", Symbol(), 
      "\n", "Price:  ", NormalizeDouble(Bid, 4), 
      "\n", "Date: ", Month(), "-", Day(), "-", Year(), " Server Time: ", Hour(), ":", Minute(), ":", Seconds(), 
   "\n");
}