/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Jose Perez 670405556"
#property link      "http://www.elportatilquebuscabas.com"

#import "user32.dll"
   int PostMessageA(int a0, int a1, int a2, int a3);
#import

extern string s00 = "** Íàñòðîéêè ñòðàòåãèè **";
extern bool buy = TRUE;
extern bool sell = TRUE;
extern bool repeat = TRUE;
extern int SizeGrid = 10;
extern string s01 = "** Stops **";
int gi_108 = 0;
extern int TakeProfit = 30;
extern int StopLoss1 = 10;
extern int StopLoss2 = 20;
extern int StopLoss3 = 30;
extern string s02 = "** Tamaño de órdenes. 0 para desactivar **";
extern double OrderLots1 = 0.1;
extern double OrderLots2 = 0.1;
extern double OrderLots3 = 0.1;
bool gi_160 = FALSE;
int gi_164 = 0;
int gi_168 = 100;
bool gi_unused_172 = FALSE;
string gs_176 = "JP_GRID";
string gs_184 = "v1.0";
extern int Slippage = 1;
extern int SecondsRepeat = 20;
double gd_200 = 0.0;
int gi_208 = 1;
int g_magic_212;
string gs_unused_216 = "";
string gs_dummy_224;
string gs_dummy_232;
string gs_dummy_240;
string gs_dummy_248;
string gs_dummy_256;
string gs_dummy_264;
string gs_dummy_272;
string gs_dummy_280;
string gs_dummy_288;
string gs_dummy_296;
int gi_unused_304 = 0;
int gi_unused_308 = -1;
string gs_unused_312 = "";
extern string sh60 = "*** Âðåìÿ ðàáîòû **********";
extern bool AlwaysEnable = TRUE;
extern string sh70 = "*** Âðåìÿ ðàáîòû. Íàñòðîéêà - 1 (00:00 - 23:59) ***";
extern bool TimeSet1 = TRUE;
extern string TimeSet1_start = "07:30";
extern string TimeSet1_stop = "14:00";
extern string sh80 = "*** Âðåìÿ ðàáîòû. Íàñòðîéêà - 2 (00:00 - 23:59) ***";
extern bool TimeSet2 = FALSE;
extern string TimeSet2_start = "14:00";
extern string TimeSet2_stop = "22:00";
extern string sh90 = "*** Âðåìÿ ðàáîòû. Íàñòðîéêà - 3 (00:00 - 23:59) ***";
extern bool TimeSet3 = FALSE;
extern string TimeSet3_start = "22:00";
extern string TimeSet3_stop = "07:30";
extern string sh100 = "*****************************************";
string gs_horario_424 = "Horario";
int gi_unused_432 = 0;
double g_bid_436 = 0.0;
int gi_unused_444 = 0;
int g_time_448 = 0;

int comprobarStopLoss(int ai_0) {
   int l_stoplevel_4 = MarketInfo(Symbol(), MODE_STOPLEVEL);
   if (ai_0 != 0 && ai_0 < l_stoplevel_4) {
      Alert("ERROR: El StopLoss mínimo en ", Symbol(), " es: ", l_stoplevel_4);
      return (0);
   }
   return (1);
}

int comprobarTakeProfit(int ai_0) {
   int l_stoplevel_4 = MarketInfo(Symbol(), MODE_STOPLEVEL);
   if (ai_0 != 0 && ai_0 < l_stoplevel_4) {
      Alert("ERROR: El TakeProfit mínimo en ", Symbol(), " es: ", l_stoplevel_4);
      return (0);
   }
   return (1);
}

double getSL(int ai_0, int ai_4, double a_price_8 = 0.0) {
   if (ai_4 == 0) return (0);
   double ld_ret_16 = 0;
   double ld_24 = MarketInfo(Symbol(), MODE_STOPLEVEL);
   ld_24 *= Point;
   if (ai_0 == 0 || ai_0 == 2 || ai_0 == 4) {
      if (a_price_8 == 0.0) {
         RefreshRates();
         a_price_8 = Ask;
      }
      ld_ret_16 = a_price_8 - ai_4 * Point;
      if (ld_ret_16 > a_price_8 - ld_24) ld_ret_16 = a_price_8 - ld_24;
   }
   if (ai_0 == 1 || ai_0 == 3 || ai_0 == 5) {
      if (a_price_8 == 0.0) {
         RefreshRates();
         a_price_8 = Bid;
      }
      ld_ret_16 = a_price_8 + ai_4 * Point;
      if (ld_ret_16 < a_price_8 + ld_24) ld_ret_16 = a_price_8 + ld_24;
   }
   return (ld_ret_16);
}

double getTP(int ai_0, int ai_4, double a_price_8 = 0.0) {
   if (ai_4 == 0) return (0);
   double ld_16 = 0;
   double ld_24 = MarketInfo(Symbol(), MODE_STOPLEVEL);
   ld_24 *= Point;
   if (ai_0 == 0 || ai_0 == 2 || ai_0 == 4) {
      if (a_price_8 == 0.0) {
         RefreshRates();
         a_price_8 = Ask;
      }
      ld_16 = a_price_8 + ai_4 * Point;
      if (ld_16 < a_price_8 + ld_24) ld_16 = a_price_8 + ld_24;
   }
   if (ai_0 == 1 || ai_0 == 3 || ai_0 == 5) {
      if (a_price_8 == 0.0) {
         RefreshRates();
         a_price_8 = Bid;
      }
      ld_16 = a_price_8 - ai_4 * Point;
      if (ld_16 > a_price_8 - ld_24) ld_16 = a_price_8 - ld_24;
   }
   ld_16 = NormalizeDouble(ld_16, Digits);
   return (ld_16);
}

int abrirPosicion(int a_cmd_0, double a_price_4 = 0.0, double ad_12 = 0.0, double ad_20 = 0.0, double a_lots_28 = 0.0, string a_comment_36 = "", int a_datetime_44 = 0) {
   double l_price_48;
   color l_color_56;
   int l_ticket_60;
   int l_error_64;
   double l_price_68;
   double l_price_76;
   if (a_comment_36 == "") a_comment_36 = gs_176 + " " + gs_184 + " " + getPeriodAsString(Period()) + ";";
   double ld_84 = (MarketInfo(Symbol(), MODE_STOPLEVEL) + 1.0) * Point;
   int li_92 = SecondsRepeat * 2;
   a_price_4 = NormalizeDouble(a_price_4, Digits);
   while (li_92 > 0) {
      RefreshRates();
      if (a_cmd_0 == OP_BUY || a_cmd_0 == OP_BUYLIMIT || a_cmd_0 == OP_BUYSTOP) {
         l_price_48 = NormalizeDouble(Ask, Digits);
         l_color_56 = Green;
      }
      if (a_cmd_0 == OP_SELL || a_cmd_0 == OP_SELLLIMIT || a_cmd_0 == OP_SELLSTOP) {
         l_price_48 = NormalizeDouble(Bid, Digits);
         l_color_56 = Red;
      }
      if (a_price_4 == 0.0) a_price_4 = l_price_48;
      if (a_lots_28 == 0.0) a_lots_28 = NormalizeLots(gd_200);
      else a_lots_28 = NormalizeLots(a_lots_28);
      if (a_cmd_0 != OP_BUY && a_cmd_0 != OP_SELL) {
         if (a_price_4 < l_price_48 && a_cmd_0 == OP_BUYSTOP) a_cmd_0 = 2;
         if (a_price_4 > l_price_48 && a_cmd_0 == OP_BUYLIMIT) a_cmd_0 = 4;
         if (a_price_4 > l_price_48 && a_cmd_0 == OP_SELLSTOP) a_cmd_0 = 3;
         if (a_price_4 < l_price_48 && a_cmd_0 == OP_SELLLIMIT) a_cmd_0 = 5;
         if (a_cmd_0 == OP_BUYLIMIT || a_cmd_0 == OP_BUYSTOP || a_cmd_0 == OP_SELLLIMIT || a_cmd_0 == OP_SELLSTOP) {
            if (MathAbs(l_price_48 - a_price_4) > ld_84) l_price_48 = a_price_4;
            else {
               if (a_cmd_0 == OP_BUYLIMIT || a_cmd_0 == OP_BUYSTOP) {
                  a_cmd_0 = 0;
                  a_datetime_44 = 0;
               }
               if (a_cmd_0 == OP_SELLLIMIT || a_cmd_0 == OP_SELLSTOP) {
                  a_cmd_0 = 1;
                  a_datetime_44 = 0;
               }
            }
         }
      }
      if (ad_12 != 0.0) l_price_68 = ad_12;
      else l_price_68 = getSL(a_cmd_0, gi_108, l_price_48);
      if (ad_20 != 0.0) l_price_76 = ad_20;
      else l_price_76 = getTP(a_cmd_0, TakeProfit, l_price_48);
      if (a_cmd_0 == OP_BUY || a_cmd_0 == OP_BUYLIMIT || a_cmd_0 == OP_BUYSTOP) {
         if (l_price_68 != 0.0 && l_price_48 - l_price_68 < ld_84) {
            if (l_price_48 - l_price_68 > 0.0) {
               l_price_68 = NormalizeDouble(l_price_48 - ld_84, Digits);
               Print("Cambiando el StopLoss al mínimo de la plataforma");
            } else {
               l_price_68 = 0;
               Print("Eliminando StopLoss incorrecto");
            }
         }
         if (l_price_76 != 0.0 && l_price_76 - l_price_48 < ld_84) {
            if (l_price_76 - l_price_48 > 0.0) {
               l_price_76 = NormalizeDouble(l_price_48 + ld_84, Digits);
               Print("Cambiando el TakeProfit al mínimo de la plataforma");
            } else {
               l_price_76 = 0;
               Print("Eliminando TakeProfit incorrecto");
            }
         }
      }
      if (a_cmd_0 == OP_SELL || a_cmd_0 == OP_SELLLIMIT || a_cmd_0 == OP_SELLSTOP) {
         if (l_price_68 != 0.0 && l_price_68 - l_price_48 < ld_84) {
            if (l_price_68 - l_price_48 > 0.0) {
               l_price_68 = NormalizeDouble(l_price_48 + ld_84, Digits);
               Print("Cambiando el StopLoss al mínimo de la plataforma");
            } else {
               l_price_68 = 0;
               Print("Eliminando StopLoss incorrecto");
            }
         }
         if (l_price_76 != 0.0 && l_price_48 - l_price_76 < ld_84) {
            if (l_price_48 - l_price_76 > 0.0) {
               l_price_76 = NormalizeDouble(l_price_48 - ld_84, Digits);
               Print("Cambiando el TakeProfit al mínimo de la plataforma");
            } else {
               l_price_76 = 0;
               Print("Eliminando TakeProfit incorrecto");
            }
         }
      }
      while (!IsTradeAllowed() || IsTradeContextBusy()) Sleep(1000);
      l_ticket_60 = OrderSend(Symbol(), a_cmd_0, a_lots_28, l_price_48, Slippage, l_price_68, l_price_76, a_comment_36, g_magic_212, a_datetime_44, l_color_56);
      if (l_ticket_60 < 0) {
         l_error_64 = GetLastError();
         Print("OrderSend falló con error #", l_error_64);
         Print("Orden: ", a_cmd_0, " L=", a_lots_28, " pa=", l_price_48, " precio=" + a_price_4 + " sp=", Slippage, " sl=", l_price_68, " tp=", l_price_76, " c=", a_comment_36, " stoplevel=", ld_84, " Bid=", Bid);
         li_92--;
         Sleep(500);
      } else return (l_ticket_60);
   }
   Alert("Se intentó operar durante " + SecondsRepeat + " segundos. Error #" + l_error_64);
   return (-1);
}

int getMagicNumber(bool ai_0 = FALSE) {
   int li_ret_4;
   if (!IsTesting()) li_ret_4 = WindowHandle(Symbol(), 0);
   else
      if (!IsVisualMode()) li_ret_4 = 23;
   if (ai_0) {
      for (int l_pos_8 = OrdersTotal() - 1; l_pos_8 >= 0; l_pos_8--) {
         OrderSelect(l_pos_8, SELECT_BY_POS);
         if (OrderSymbol() == Symbol()) {
            if (StringSubstr(OrderComment(), 0, StringLen(gs_176)) == gs_176 && StringFind(OrderComment(), " ", StringLen(gs_176) + 1) == -1 || StringSubstr(OrderComment(), StringFind(OrderComment(), " ", StringLen(gs_176) +
               1) + 1, StringLen(getPeriodAsString(Period()))) == getPeriodAsString(Period())) {
               Print("Retomando orden " + OrderTicket());
               li_ret_4 = OrderMagicNumber();
               break;
            }
         }
      }
   }
   return (li_ret_4);
}

void ajustarTrailingStopTodas(int ai_0, int ai_4, int ai_8 = 0) {
   for (int l_pos_12 = 0; l_pos_12 < OrdersTotal(); l_pos_12++)
      if ((OrderSelect(l_pos_12, SELECT_BY_POS) && OrderMagicNumber() == g_magic_212)) ajustarTrailingStop(OrderTicket(), ai_0, ai_4, ai_8);
}

int ajustarTrailingStop(int a_ticket_0, int ai_4, int ai_8, int ai_12 = 0) {
   int li_20;
   double l_price_24;
   double ld_32;
   int li_40;
   if (!OrderSelect(a_ticket_0, SELECT_BY_TICKET)) return (0);
   if (ai_8 < MarketInfo(OrderSymbol(), MODE_STOPLEVEL)) {
      Print("No se puede modificar el SL, la distancia mínima requerida es " + DoubleToStr(MarketInfo(OrderSymbol(), MODE_STOPLEVEL), 0) + " y se ha calculado " + DoubleToStr(ai_8, 0));
      return (0);
   }
   if (OrderType() == OP_BUY || OrderType() == OP_BUYLIMIT || OrderType() == OP_BUYSTOP) li_20 = (OrderClosePrice() - OrderOpenPrice()) / MarketInfo(OrderSymbol(), MODE_POINT);
   else
      if (OrderType() == OP_SELL || OrderType() == OP_SELLLIMIT || OrderType() == OP_SELLSTOP) li_20 = (OrderOpenPrice() - OrderClosePrice()) / MarketInfo(OrderSymbol(), MODE_POINT);
   if (li_20 <= 0) return (0);
   if (li_20 > ai_4) {
      if (OrderType() == OP_BUY || OrderType() == OP_BUYLIMIT || OrderType() == OP_BUYSTOP) {
         l_price_24 = OrderOpenPrice() + (li_20 - ai_8) * Point;
         l_price_24 = NormalizeDouble(l_price_24, Digits);
         ld_32 = l_price_24 - ai_12 * Point;
         if (NormalizeDouble(OrderStopLoss(), Digits) < NormalizeDouble(ld_32, Digits) || OrderStopLoss() == 0.0) {
            li_40 = SecondsRepeat * 2;
            while (li_40 > 0) {
               while (!IsTradeAllowed() || IsTradeContextBusy()) Sleep(1000);
               if (OrderModify(OrderTicket(), OrderOpenPrice(), l_price_24, OrderTakeProfit(), 0, Black)) return (1);
               Print("Error " + GetLastError() + " al ajustar TrailingStop, nuevoStop=" + l_price_24 + ", viejoStop=" + OrderStopLoss());
               li_40--;
               Sleep(500);
            }
         }
      }
      if (OrderType() == OP_SELL || OrderType() == OP_SELLLIMIT || OrderType() == OP_SELLSTOP) {
         l_price_24 = OrderOpenPrice() - (li_20 - ai_8) * Point;
         l_price_24 = NormalizeDouble(l_price_24, Digits);
         ld_32 = l_price_24 + ai_12 * Point;
         if (NormalizeDouble(OrderStopLoss(), Digits) > NormalizeDouble(ld_32, Digits) || OrderStopLoss() == 0.0) {
            li_40 = SecondsRepeat * 2;
            while (li_40 > 0) {
               while (!IsTradeAllowed() || IsTradeContextBusy()) Sleep(1000);
               if (OrderModify(OrderTicket(), OrderOpenPrice(), l_price_24, OrderTakeProfit(), 0, Black)) return (1);
               Print("Error " + GetLastError() + " al ajustar TrailingStop, nuevoStop=" + l_price_24 + ", viejoStop=" + OrderStopLoss());
               li_40--;
               Sleep(500);
            }
         }
      }
   }
   return (0);
}

string getPeriodAsString(int a_timeframe_0 = 0) {
   if (a_timeframe_0 == 0) a_timeframe_0 = Period();
   switch (a_timeframe_0) {
   case PERIOD_M1:
      return ("M1");
   case PERIOD_M5:
      return ("M5");
   case PERIOD_M15:
      return ("M15");
   case PERIOD_M30:
      return ("M30");
   case PERIOD_H1:
      return ("H1");
   case PERIOD_H4:
      return ("H4");
   case PERIOD_D1:
      return ("D1");
   case PERIOD_W1:
      return ("W1");
   case PERIOD_MN1:
      return ("MN1");
   }
   return ("");
}

double NormalizeLots(double ad_0) {
   double ld_8 = ad_0;
   double l_minlot_16 = MarketInfo(Symbol(), MODE_MINLOT);
   if (ld_8 < l_minlot_16) return (0);
   double l_maxlot_24 = MarketInfo(Symbol(), MODE_MAXLOT);
   if (ld_8 > l_maxlot_24) return (l_maxlot_24);
   double l_lotstep_32 = MarketInfo(Symbol(), MODE_LOTSTEP);
   int li_40 = MathRound(ld_8 / l_lotstep_32);
   ld_8 = l_lotstep_32 * li_40;
   return (NormalizeDouble(ld_8, 2));
}

int enHorario?() {
   if (AlwaysEnable) return (1);
   string l_time2str_0 = TimeToStr(TimeCurrent(), TIME_SECONDS);
   int l_str2time_8 = StrToTime(l_time2str_0);
   int l_str2time_12 = StrToTime(TimeSet1_start);
   int l_str2time_16 = StrToTime(TimeSet1_stop);
   int l_str2time_20 = StrToTime(TimeSet2_start);
   int l_str2time_24 = StrToTime(TimeSet2_stop);
   int l_str2time_28 = StrToTime(TimeSet3_start);
   int l_str2time_32 = StrToTime(TimeSet3_stop);
   if (TimeSet1) {
      if (l_str2time_12 < l_str2time_16) {
         if (l_str2time_8 >= l_str2time_12 && l_str2time_8 < l_str2time_16) return (1);
      } else
         if ((l_str2time_8 >= l_str2time_12 && l_str2time_8 <= StrToTime("23:59:59")) || l_str2time_8 < l_str2time_16) return (1);
   }
   if (TimeSet2) {
      if (l_str2time_20 < l_str2time_24) {
         if (l_str2time_8 >= l_str2time_20 && l_str2time_8 < l_str2time_24) return (1);
      } else
         if ((l_str2time_8 >= l_str2time_20 && l_str2time_8 <= StrToTime("23:59:59")) || l_str2time_8 < l_str2time_24) return (1);
   }
   if (TimeSet3) {
      if (l_str2time_28 < l_str2time_32) {
         if (l_str2time_8 >= l_str2time_28 && l_str2time_8 < l_str2time_32) return (1);
      } else
         if ((l_str2time_8 >= l_str2time_28 && l_str2time_8 <= StrToTime("23:59:59")) || l_str2time_8 < l_str2time_32) return (1);
   }
   return (0);
}

void mostrarGraficoHorario(bool ai_0) {
   string l_text_4;
   int l_datetime_12;
   int l_hour_16;
   int l_minute_20;
   if (IsTesting() && !IsVisualMode()) return;
   if (AlwaysEnable == 0) {
      l_text_4 = "Cargando datos...";
      if (ObjectFind(gs_horario_424) == -1) {
         ObjectCreate(gs_horario_424, OBJ_LABEL, 0, 0, 0);
         ObjectSet(gs_horario_424, OBJPROP_CORNER, 2);
         ObjectSet(gs_horario_424, OBJPROP_XDISTANCE, 20);
         ObjectSet(gs_horario_424, OBJPROP_YDISTANCE, 10);
         ObjectSetText(gs_horario_424, l_text_4, 14, "Times New Roman", Lime);
      }
      l_datetime_12 = TimeCurrent();
      l_text_4 = "[";
      l_hour_16 = TimeHour(l_datetime_12);
      if (l_hour_16 < 10) l_text_4 = l_text_4 + "0";
      l_text_4 = l_text_4 + l_hour_16 + ":";
      l_minute_20 = TimeMinute(l_datetime_12);
      if (l_minute_20 < 10) l_text_4 = l_text_4 + "0";
      l_text_4 = l_text_4 + l_minute_20 + "]";
      if (ai_0) ObjectSetText(gs_horario_424, l_text_4 + " Dentro de horario.", 14, "Times New Roman", Lime);
      else ObjectSetText(gs_horario_424, l_text_4 + " Fuera de horario.", 14, "Times New Roman", Red);
   }
}

int init() {
   if (Digits == 3 || Digits == 5) gi_208 = 10;
   else gi_208 = 1;
   gi_108 *= gi_208;
   StopLoss1 *= gi_208;
   StopLoss2 *= gi_208;
   StopLoss3 *= gi_208;
   TakeProfit *= gi_208;
   SizeGrid *= gi_208;
   Slippage *= gi_208;
   gi_168 *= gi_208;
   if (!comprobarStopLoss(StopLoss1)) {
      Alert("Se elimina el StopLoss1 al ser menor que el mínimo para " + Symbol() + ": " + DoubleToStr(MarketInfo(Symbol(), MODE_STOPLEVEL), 0));
      StopLoss1 = 0;
   }
   if (!comprobarStopLoss(StopLoss2)) {
      Alert("Se elimina el StopLoss2 al ser menor que el mínimo para " + Symbol() + ": " + DoubleToStr(MarketInfo(Symbol(), MODE_STOPLEVEL), 0));
      StopLoss2 = 0;
   }
   if (!comprobarStopLoss(StopLoss3)) {
      Alert("Se elimina el StopLoss3 al ser menor que el mínimo para " + Symbol() + ": " + DoubleToStr(MarketInfo(Symbol(), MODE_STOPLEVEL), 0));
      StopLoss3 = 0;
   }
   if (!comprobarStopLoss(gi_168)) {
      Alert("Se elimina el TrailingStopDistancia al ser menor que el mínimo para " + Symbol() + ": " + DoubleToStr(MarketInfo(Symbol(), MODE_STOPLEVEL), 0));
      gi_168 = 0;
   }
   if (!comprobarTakeProfit(TakeProfit)) {
      Alert("Se elimina el TakeProfit al ser menor que el mínimo para " + Symbol() + ": " + DoubleToStr(MarketInfo(Symbol(), MODE_STOPLEVEL), 0));
      TakeProfit = 0;
   }
   g_magic_212 = getMagicNumber(1);
   return (0);
}

int start() {
   mostrarGraficoHorario(enHorario?());
   if (gi_160) ajustarTrailingStopTodas(gi_164, gi_168);
   if (g_time_448 == 0 || repeat) {
      abrirPosiciones();
      g_time_448 = Time[0];
   }
   return (0);
}

int deinit() {
   ObjectDelete(gs_horario_424);
   return (0);
}

void abrirPosiciones() {
   int li_4;
   int li_8;
   int li_16;
   int li_20;
   int li_24;
   bool li_0 = FALSE;
   if (g_bid_436 == 0.0) {
      li_0 = TRUE;
      g_bid_436 = Bid;
      gi_unused_444 = (Ask - Bid) / Point;
   } else {
      if (repeat) {
         li_4 = g_bid_436 / Point / gi_208;
         li_8 = Bid / Point / gi_208;
         if (li_8 == li_4) li_0 = TRUE;
         else {
            if (li_8 > li_4) {
               while (li_8 > li_4) {
                  li_8 -= SizeGrid / gi_208;
                  if (li_8 == li_4) {
                     li_0 = TRUE;
                     break;
                  }
               }
            } else {
               if (li_8 < li_4) {
                  while (li_8 < li_4) {
                     li_8 += SizeGrid / gi_208;
                     if (li_8 == li_4) {
                        li_0 = TRUE;
                        break;
                     }
                  }
               }
            }
         }
         if (li_0) {
            for (int l_pos_12 = 0; l_pos_12 < OrdersTotal(); l_pos_12++) {
               if ((OrderSelect(l_pos_12, SELECT_BY_POS) && OrderMagicNumber() == g_magic_212)) {
                  li_16 = Bid / Point / gi_208;
                  li_20 = Ask / Point / gi_208;
                  li_24 = OrderOpenPrice() / Point / gi_208;
                  if ((OrderType() == OP_SELL && MathAbs(li_24 - li_16) < 2.0) || (OrderType() == OP_BUY && MathAbs(li_24 - li_20) < 2.0)) {
                     li_0 = FALSE;
                     break;
                  }
               }
            }
         }
      }
   }
   if (li_0) {
      if (buy) {
         abrirPosicion(OP_BUY, 0, getSL(0, StopLoss1), getTP(0, TakeProfit), OrderLots1);
         abrirPosicion(OP_BUY, 0, getSL(0, StopLoss2), getTP(0, TakeProfit), OrderLots2);
         abrirPosicion(OP_BUY, 0, getSL(0, StopLoss3), getTP(0, TakeProfit), OrderLots3);
      }
      if (sell) {
         abrirPosicion(OP_SELL, 0, getSL(1, StopLoss1), getTP(1, TakeProfit), OrderLots1);
         abrirPosicion(OP_SELL, 0, getSL(1, StopLoss2), getTP(1, TakeProfit), OrderLots2);
         abrirPosicion(OP_SELL, 0, getSL(1, StopLoss3), getTP(1, TakeProfit), OrderLots3);
      }
   }
}